### ISSUE TITLE
Are the relations exposed to the API or any of the output formats in any way?

### ISSUE THREAD

**Issue by masonn** [omeka/plugin-ItemRelations#16]
I checked RDF (?output=dc-rdf) and the API but don't see any of my defined relations.  Are these relations exposed anywhere other than the public pages?

**Comment by zerocrates** [comment]
You're correct that the current release doesn't expose the relations in any machine-readable format.

I've just added a new branch "api" that adds an item_relations API endpoint and links out from the items to expose relations.

**Comment by masonn** [comment]
Thank you so much, I really appreciate you taking the time to address this.

**Comment by zerocrates** [comment]
This will be in the 2.2 release.
