### ISSUE TITLE
Custom vocab property description input seems unnecessarily large

### ISSUE THREAD

**Issue by sharonmleon** [omeka/plugin-ItemRelations#17]
![Screenshot 2021-09-08 at 14-00-02 Edit Custom Vocabulary · SMLNew · Omeka Admin](https://user-images.githubusercontent.com/741480/132560866-71f0d0aa-8cc5-4350-b60c-779a21dcc4a8.png)

**Comment by kimisgold** [comment]
There's a fix for this that's ready for a look.

**Comment by sharonmleon** [comment]
Looks good. Thanks!
